{
    "DISCLAIMER": "USER-NOTICE: The results in this file were produced with the PMP v1.1 (https://github.com/PCMDI/pcmdi_metrics). They are for research purposes only. They are subject to ongoing quality control and change as the PMP software advances, interpolation methods are modified, observational data sets are updated, problems with model data are corrected, etc. Use of these results for research (presentation, publications, etc.) should reference: Gleckler, P. J., C. Doutriaux, P. J. Durack, K. E. Taylor, Y. Zhang, and D. N. Williams, E. Mason, and J. Servonnat (2016), A more powerful reality test for climate models, Eos, 97, doi:10.1029/2016EO051663. If any problems are uncovered in using these results please contact the PMP development team at pcmdi-metrics@llnl.gov\n",
    "RESULTS": {
        "GFDL-CM3": {
            "SimulationDescription": {
                "ModellingGroup": "N/A",
                "ModelFreeSpace": "N/A",
                "MIPTable": "Omon",
                "creation_date": "N/A",
                "ModelActivity": "N/A",
                "Experiment": "N/A",
                "Realization": "r1i1p1",
                "Model": "GFDL-CM3"
            },
            "JPL-Aquarius-v2": {
                "source": {
                    "RefName": "JPL-Aquarius-v2",
                    "MD5sum": "648c3f92abe91223ac24645cac653e6f",
                    "period": "201108-201304",
                    "filename": "sos_pcmdi-metrics_Omon_JPL-Aquarius-v2_201108-201304-clim.nc",
                    "shape": "(12, 180, 360)",
                    "CMIP_CMOR_TABLE": "Omon",
                    "RefTrackingDate": "Wed Jan 15 10:29:05 2014"
                },
                "r1i1p1": {
                    "TROPICS": {
                        "bias_xy": {
                            "ann": "-0.162",
                            "son": "-0.190",
                            "mam": "-0.105",
                            "jja": "-0.173",
                            "djf": "-0.178"
                        },
                        "cor_xy": {
                            "ann": "0.851",
                            "son": "0.84",
                            "mam": "0.79",
                            "jja": "0.80",
                            "djf": "0.85"
                        },
                        "mae_xy": {
                            "ann": "0.421",
                            "son": "0.462",
                            "mam": "0.460",
                            "jja": "0.478",
                            "djf": "0.417"
                        },
                        "mean-obs_xy": {
                            "ann": "35.141",
                            "son": "35.146",
                            "mam": "35.094",
                            "jja": "35.182",
                            "djf": "35.168"
                        },
                        "mean_xy": {
                            "ann": "34.936",
                            "son": "34.909",
                            "mam": "34.937",
                            "jja": "34.951",
                            "djf": "34.946"
                        },
                        "rms_devzm": {
                            "ann": "0.432"
                        },
                        "rms_xy": {
                            "ann": "0.528",
                            "son": "0.577",
                            "mam": "0.600",
                            "jja": "0.606",
                            "djf": "0.538"
                        },
                        "rms_xyt": {
                            "ann": "0.612"
                        },
                        "rms_y": {
                            "ann": "0.313"
                        },
                        "rmsc_xy": {
                            "ann": "0.502",
                            "son": "0.545",
                            "mam": "0.591",
                            "jja": "0.581",
                            "djf": "0.508"
                        },
                        "std-obs_xy": {
                            "ann": "0.953",
                            "son": "0.998",
                            "mam": "0.940",
                            "jja": "0.954",
                            "djf": "0.975"
                        },
                        "std-obs_xy_devzm": {
                            "ann": "0.829"
                        },
                        "std-obs_xyt": {
                            "ann": "0.982"
                        },
                        "std_xy": {
                            "ann": "0.949",
                            "son": "0.997",
                            "mam": "0.981",
                            "jja": "0.950",
                            "djf": "0.967"
                        },
                        "std_xy_devzm": {
                            "ann": "0.854"
                        },
                        "std_xyt": {
                            "ann": "0.984"
                        }
                    },
                    "global": {
                        "bias_xy": {
                            "ann": "0.021",
                            "son": "-0.192",
                            "mam": "0.021",
                            "jja": "-0.123",
                            "djf": "-0.086"
                        },
                        "cor_xy": {
                            "ann": "0.778",
                            "son": "0.85",
                            "mam": "0.82",
                            "jja": "0.82",
                            "djf": "0.84"
                        },
                        "mae_xy": {
                            "ann": "0.528",
                            "son": "0.455",
                            "mam": "0.481",
                            "jja": "0.475",
                            "djf": "0.436"
                        },
                        "mean-obs_xy": {
                            "ann": "34.636",
                            "son": "34.913",
                            "mam": "34.717",
                            "jja": "34.851",
                            "djf": "34.806"
                        },
                        "mean_xy": {
                            "ann": "34.523",
                            "son": "34.505",
                            "mam": "34.542",
                            "jja": "34.513",
                            "djf": "34.535"
                        },
                        "rms_devzm": {
                            "ann": "0.767"
                        },
                        "rms_xy": {
                            "ann": "0.984",
                            "son": "0.584",
                            "mam": "0.636",
                            "jja": "0.650",
                            "djf": "0.612"
                        },
                        "rms_xyt": {
                            "ann": "0.763"
                        },
                        "rms_y": {
                            "ann": "1.645"
                        },
                        "rmsc_xy": {
                            "ann": "0.984",
                            "son": "0.552",
                            "mam": "0.636",
                            "jja": "0.638",
                            "djf": "0.606"
                        },
                        "std-obs_xy": {
                            "ann": "1.549",
                            "son": "1.048",
                            "mam": "1.121",
                            "jja": "1.106",
                            "djf": "1.121"
                        },
                        "std-obs_xy_devzm": {
                            "ann": "1.023"
                        },
                        "std-obs_xyt": {
                            "ann": "1.253"
                        },
                        "std_xy": {
                            "ann": "1.611",
                            "son": "1.650",
                            "mam": "1.586",
                            "jja": "1.662",
                            "djf": "1.593"
                        },
                        "std_xy_devzm": {
                            "ann": "1.356"
                        },
                        "std_xyt": {
                            "ann": "1.628"
                        }
                    },
                    "NHEX": {
                        "bias_xy": {
                            "ann": "0.491",
                            "son": "0.048",
                            "mam": "0.087",
                            "jja": "-0.149",
                            "djf": "0.302"
                        },
                        "cor_xy": {
                            "ann": "0.742",
                            "son": "0.91",
                            "mam": "0.92",
                            "jja": "0.87",
                            "djf": "0.85"
                        },
                        "mae_xy": {
                            "ann": "0.874",
                            "son": "0.459",
                            "mam": "0.411",
                            "jja": "0.490",
                            "djf": "0.572"
                        },
                        "mean-obs_xy": {
                            "ann": "33.637",
                            "son": "34.316",
                            "mam": "34.446",
                            "jja": "34.376",
                            "djf": "34.230"
                        },
                        "mean_xy": {
                            "ann": "33.554",
                            "son": "33.445",
                            "mam": "33.713",
                            "jja": "33.399",
                            "djf": "33.664"
                        },
                        "rms_devzm": {
                            "ann": "1.668"
                        },
                        "rms_xy": {
                            "ann": "2.004",
                            "son": "0.674",
                            "mam": "0.587",
                            "jja": "0.884",
                            "djf": "0.882"
                        },
                        "rms_xyt": {
                            "ann": "1.230"
                        },
                        "rms_y": {
                            "ann": "2.169"
                        },
                        "rmsc_xy": {
                            "ann": "1.943",
                            "son": "0.672",
                            "mam": "0.580",
                            "jja": "0.872",
                            "djf": "0.829"
                        },
                        "std-obs_xy": {
                            "ann": "2.877",
                            "son": "1.455",
                            "mam": "1.383",
                            "jja": "1.524",
                            "djf": "1.573"
                        },
                        "std-obs_xy_devzm": {
                            "ann": "2.020"
                        },
                        "std-obs_xyt": {
                            "ann": "1.996"
                        },
                        "std_xy": {
                            "ann": "3.299",
                            "son": "3.362",
                            "mam": "3.217",
                            "jja": "3.399",
                            "djf": "3.241"
                        },
                        "std_xy_devzm": {
                            "ann": "2.952"
                        },
                        "std_xyt": {
                            "ann": "3.312"
                        }
                    },
                    "SHEX": {
                        "bias_xy": {
                            "ann": "0.122",
                            "son": "-0.306",
                            "mam": "0.223",
                            "jja": "-0.013",
                            "djf": "-0.083"
                        },
                        "cor_xy": {
                            "ann": "0.678",
                            "son": "0.79",
                            "mam": "0.79",
                            "jja": "0.78",
                            "djf": "0.78"
                        },
                        "mae_xy": {
                            "ann": "0.555",
                            "son": "0.440",
                            "mam": "0.550",
                            "jja": "0.462",
                            "djf": "0.415"
                        },
                        "mean-obs_xy": {
                            "ann": "34.232",
                            "son": "34.739",
                            "mam": "34.144",
                            "jja": "34.431",
                            "djf": "34.422"
                        },
                        "mean_xy": {
                            "ann": "34.334",
                            "son": "34.378",
                            "mam": "34.306",
                            "jja": "34.356",
                            "djf": "34.295"
                        },
                        "rms_devzm": {
                            "ann": "0.547"
                        },
                        "rms_xy": {
                            "ann": "0.887",
                            "son": "0.552",
                            "mam": "0.716",
                            "jja": "0.596",
                            "djf": "0.601"
                        },
                        "rms_xyt": {
                            "ann": "0.739"
                        },
                        "rms_y": {
                            "ann": "1.898"
                        },
                        "rmsc_xy": {
                            "ann": "0.878",
                            "son": "0.460",
                            "mam": "0.680",
                            "jja": "0.596",
                            "djf": "0.596"
                        },
                        "std-obs_xy": {
                            "ann": "1.130",
                            "son": "0.725",
                            "mam": "1.020",
                            "jja": "0.897",
                            "djf": "0.892"
                        },
                        "std-obs_xy_devzm": {
                            "ann": "0.564"
                        },
                        "std-obs_xyt": {
                            "ann": "1.013"
                        },
                        "std_xy": {
                            "ann": "0.488",
                            "son": "0.441",
                            "mam": "0.540",
                            "jja": "0.475",
                            "djf": "0.519"
                        },
                        "std_xy_devzm": {
                            "ann": "0.249"
                        },
                        "std_xyt": {
                            "ann": "0.499"
                        }
                    }
                }
            },
            "InputRegionMD5": null,
            "InputClimatologyFileName": "sos_GFDL-CM3_Omon_historical_000101-010012-clim.nc",
            "units": "psu",
            "InputClimatologyMD5": "819e0bb5a3df09c0d81ccea9f4c9ae41",
            "InputRegionFileName": null
        }
    },
    "Variable": {
        "id": "sos"
    },
    "json_version": 3.0,
    "References": {
        "JPL-Aquarius-v2": {
            "RefName": "JPL-Aquarius-v2",
            "MD5sum": "648c3f92abe91223ac24645cac653e6f",
            "period": "201108-201304",
            "filename": "sos_pcmdi-metrics_Omon_JPL-Aquarius-v2_201108-201304-clim.nc",
            "shape": "(12, 180, 360)",
            "CMIP_CMOR_TABLE": "Omon",
            "RefTrackingDate": "Wed Jan 15 10:29:05 2014"
        }
    },
    "RegionalMasking": {
        "TROPICS": {
            "domain": {
                "TROPICS": "cdutil.region.domain(latitude=(-30.0, 30))"
            },
            "id": "TROPICS"
        },
        "global": {
            "id": "global"
        },
        "NHEX": {
            "domain": {
                "NHEX": "cdutil.region.domain(latitude=(30.0, 90))"
            },
            "id": "NHEX"
        },
        "SHEX": {
            "domain": {
                "SHEX": "cdutil.region.domain(latitude=(-90.0, -30))"
            },
            "id": "SHEX"
        }
    },
    "GridInfo": {
        "GridResolution": [
            25,
            144
        ],
        "GridName": "2.5x2.5",
        "RegridMethod": "linear",
        "RegridTool": "esmf"
    },
    "METRICS": {
        "rms_xyt": {
            "Abstract": "Compute Spatial and Temporal Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatio-Temporal Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "rms_xy": {
            "Abstract": "Compute Spatial Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "rmsc_xy": {
            "Abstract": "Compute Centered Spatial Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "bias_xy": {
            "Abstract": "Compute Full Average of Model - Observation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Bias"
        },
        "mae_xy": {
            "Abstract": "Compute Full Average of Absolute Difference Between Model And Observation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Mean Absolute Error"
        },
        "cor_xy": {
            "Abstract": "Compute Spatial Correlation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Correlation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "mean_xy": {
            "Abstract": "Area Mean (area weighted)",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Mean"
        },
        "std_xy": {
            "Abstract": "Compute Spatial Standard Deviation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Standard Deviation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "std_xyt": {
            "Abstract": "Compute Space-Time Standard Deviation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial-temporal Standard Deviation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "seasonal_mean": {
            "Abstract": "Compute Seasonal Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Seasonal Mean",
            "Comments": "Assumes input are 12 months climatology"
        },
        "annual_mean": {
            "Abstract": "Compute Annual Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Annual Mean",
            "Comments": "Assumes input are 12 months climatology",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "zonal_mean": {
            "Abstract": "Compute Zonal Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Zonal Mean",
            "Comments": "",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        }
    },
    "json_structure": [
        "model",
        "reference",
        "rip",
        "region",
        "statistic",
        "season"
    ],
    "provenance": {
        "platform": {
            "OS": "Darwin",
            "Version": "16.7.0",
            "Name": "loki"
        },
        "userId": "doutriaux1",
        "osAccess": false,
        "commandLine": "/Users/doutriaux1/anaconda2/envs/cdat8/bin/pcmdi_metrics_driver.py -p /git/pcmdi_metrics/tests/pcmdi/salinity_test.py",
        "date": "2018-05-03 09:25:17",
        "conda": {
            "Version": "4.5.1",
            "buildVersion": "3.9.1",
            "PythonVersion": "2.7.14.final.0",
            "Platform": "osx-64"
        },
        "packages": {
            "blas": "1.0.1",
            "cdms": "3.0",
            "CDP": "1.3.2",
            "cdtime": "3.0",
            "cdutil": "8.0",
            "clapack": "3.2.1",
            "lapack": "3.6.1",
            "esmf": "7.1.0r",
            "esmpy": "7.1.0r",
            "genutil": "8.0",
            "python": "2.7.14",
            "matplotlib": "2.2.2",
            "mesalib": "17.2.0",
            "numpy": "1.14.2",
            "vcs": "8.0.2018.04.27.14.53.gfc2e5fc5",
            "vtk": "8.0.1.8.0",
            "PMP": "ga068fe0",
            "PMPObs": null
        },
        "openGL": {
            "vendor": "ATI Technologies Inc.",
            "renderer": "AMD Radeon Pro 455 OpenGL Engine",
            "version": "2.1 ATI-1.51.8",
            "shading language version": "1.20",
            "GLX": {
                "client": {
                    "vendor": "Mesa Project and SGI",
                    "version": "1.4"
                },
                "version": "1.4",
                "server": {
                    "vendor": "SGI",
                    "version": "1.4"
                }
            }
        }
    }
}