message("[INFO] CHECKING IF VERSION ${MYVERSION} is BETWEEN ${MINVERSION} AND ${MAXVERSION}")
if ( ${MYVERSION} VERSION_GREATER ${MINVERSION} AND ${MYVERSION} VERSION_LESS ${MAXVERSION})
  message("[INFO] VERSION OK")
else()
  message(FATAL_ERROR "[INFO] BAD VERSION")
endif()

