blank_issues_enabled: true
contact_links:
    - name: Questions (PMP)
      url: https://github.com/PCMDI/pcmdi_metrics/discussions
      about: |
          Ask questions and discuss with other PMP community members here. Please
          browse the PMP Discussions Forum or PMP documentation first before asking a
          question to make sure it is not already answered. If you can't find an
          answer, please include a self-contained reproducible example with your
          question if possible. Thanks!

