nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v pr > cmip6_hist_pr_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v tas > cmip6_hist_tas_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v ta_850 > cmip6_hist_ta850_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v ta_200 > cmip6_hist_ta200_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v ua_850 > cmip6_hist_ua850_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v ua_200 > cmip6_hist_ua200_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v va_850 > cmip6_hist_va850_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v va_200 > cmip6_hist_va200_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v zg_500 > cmip6_hist_zg500_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rlut > cmip6_hist_rlut_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rsut > cmip6_hist_rsut_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rltcre > cmip6_hist_rltcre_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rstcre > cmip6_hist_rstcre_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rt > cmip6_hist_rt_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rst > cmip6_hist_rst_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rsdt > cmip6_hist_rsdt_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rsutcs > cmip6_hist_rsutcs_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rlutcs > cmip6_hist_rlutcs_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rsds > cmip6_hist_rsds_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rlds > cmip6_hist_rlds_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rlus > cmip6_hist_rlus_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rldscs > cmip6_hist_rldscs_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v rsdscs > cmip6_hist_rsdscs_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v tauu > cmip6_hist_tauu_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v tauu > cmip6_hist_tauu_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v psl > cmip6_hist_psl_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v sfcWind > cmip6_hist_sfcWind_v201217.log &
nohup mean_climate_driver.py -p pcmdi_MIP_EXP_pmp_parameterfile.py -v prw > cmip6_hist_prw_v201217.log &

