obs_dic_in = {'rlut': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rst': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsut': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsds': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rlds': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsdt': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsdscs': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rldscs': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rlus': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsus': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rlutcs': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsutcs': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rstcre': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rltcre': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rsuscs': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'rt': {'default': 'CERES-EBAF-4-1','alternate1': 'CERES-EBAF-4-0'},
              'pr': {'default': 'GPCP-2-3',
                     'alternate1': 'TRMM-3B43v-7',
                     'alternate2': 'CMAP-V1902',
                     'alternate3': 'MSWEP-V280'}, 
              'prw': {'default': 'REMSS-PRW-v07r01'},
              'sfcWind': {'default': 'REMSS-PRW-v07r01','alternate1':'ERA-INT'},
              'tas': {'default': 'ERA-5',
                      'alternate1': 'ERA-INT',
                      'alternate2': 'ERA-40'},
              'psl': {'default': 'ERA-5',
                      'alternate2': 'ERA-40',
                      'alternate1': 'ERA-INT'},
              'ua':  {'default': 'ERA-5',
                     'alternate1': 'ERA-INT',
                     'alternate3': 'JRA25',
                     'alternate2': 'ERA-40'},
              'va': {'default': 'ERA-5',
                     'alternate1': 'ERA-INT',
                     'alternate2': 'ERA-40'},
              'uas': {'default': 'ERA-5',
                      'alternate1': 'ERA-INT',
                      'alternate2': 'ERA-40'},
              'hfls':{'default': 'ERA-INT','alternate1':'TropFlux-1-0'},
              'hfns':{'default': 'ERA-INT','alternate1':'TropFlux-1-0'},
              'hfss':{'default': 'ERA-INT','alternate1':'TropFlux-1-0'},
              'hus': {'default': 'ERA-INT',
                      'alternate2': 'JRA25',
                      'alternate1': 'ERA-40'},
              'hur': {'default': 'ERA-INT',
                      'alternate1': 'ERA-40'},
              'vas': {'default': 'ERA-5',
                      'alternate2': 'ERA-INT',
                      'alternate1': 'ERA-40'},
              'ta': {'default': 'ERA-5',
                     'alternate2': 'ERA-INT',
                     'alternate1': 'ERA-40'},
              'zg': {'default': 'ERA-5',
                     'alternate1': 'ERA-INT',
                     'alternate2': 'ERA-40'},
              'tauu': {'default': 'ERA-INT',
                       'alternate2': 'JRA25',
                       'alternate1': 'ERA-40'},
              'tauv': {'default': 'ERA-INT',
                       'alternate2': 'JRA25',
                       'alternate1': 'ERA-40'},
              'tos': {'default': 'UKMETOFFICE-HadISST-v1-1'},
              'zos': {'default': 'AVISO-1-0'},
              'sos': {'default': 'NODC-WOA09'},
              'ts': {'default': 'ERA-5', 'alternate1':'HadISST-1-1','alternate2':'OISST-L4-AVHRR-only-v2'},
              'thetao': {'default': 'WOA13v2',
                         'alternate1': 'UCSD',
                         'alternate2': 'Hosoda-MOAA-PGV',
                         'alternate3': 'IPRC'}
              }


