{
    "DISCLAIMER": "USER-NOTICE: The results in this file were produced with the PMP v1.1 (https://github.com/PCMDI/pcmdi_metrics). They are for research purposes only. They are subject to ongoing quality control and change as the PMP software advances, interpolation methods are modified, observational data sets are updated, problems with model data are corrected, etc. Use of these results for research (presentation, publications, etc.) should reference: Gleckler, P. J., C. Doutriaux, P. J. Durack, K. E. Taylor, Y. Zhang, and D. N. Williams, E. Mason, and J. Servonnat (2016), A more powerful reality test for climate models, Eos, 97, doi:10.1029/2016EO051663. If any problems are uncovered in using these results please contact the PMP development team at pcmdi-metrics@llnl.gov\n",
    "RESULTS": {
        "GFDL-ESM2G": {
            "SimulationDescription": {
                "Center": "N/A",
                "ModellingGroup": "NOAA GFDL",
                "ModelFreeSpace": "N/A",
                "MIPTable": "Omon",
                "creation_date": "2012-01-10T20:19:59Z",
                "ModelActivity": "CMIP5",
                "Experiment": "historical",
                "Realization": "r1i1p1",
                "Model": "GFDL-ESM2G",
                "Login": "N/A",
                "SimTrackingDate": "2012-01-10T20:19:59Z"
            },
            "default": {
                "source": "UKMETOFFICE-HadISST-v1-1",
                "r1i1p1": {
                    "TROPICS": {
                        "bias_xy": {
                            "ann": "-0.591",
                            "son": "-0.641",
                            "mam": "-0.552",
                            "jja": "-0.572",
                            "djf": "-0.599",
                            "CalendarMonths": []
                        },
                        "cor_xy": {
                            "ann": "0.928",
                            "son": "0.93",
                            "mam": "0.90",
                            "jja": "0.94",
                            "djf": "0.90",
                            "CalendarMonths": []
                        },
                        "custom_ref_min": 280.54689315404653,
                        "mae_xy": {
                            "ann": "0.888",
                            "son": "1.021",
                            "mam": "0.999",
                            "jja": "0.946",
                            "djf": "0.995",
                            "CalendarMonths": []
                        },
                        "mean-obs_xy": {
                            "ann": "299.283",
                            "son": "299.089",
                            "mam": "299.698",
                            "jja": "299.085",
                            "djf": "299.265",
                            "CalendarMonths": []
                        },
                        "mean_xy": {
                            "ann": "298.664",
                            "son": "298.405",
                            "mam": "299.128",
                            "jja": "298.476",
                            "djf": "298.654",
                            "CalendarMonths": []
                        },
                        "rms_devzm": {
                            "ann": "0.874"
                        },
                        "rms_xy": {
                            "ann": "1.098",
                            "son": "1.285",
                            "mam": "1.300",
                            "jja": "1.195",
                            "djf": "1.240",
                            "CalendarMonths": []
                        },
                        "rms_xyt": {
                            "ann": "1.305"
                        },
                        "rms_y": {
                            "ann": "0.709"
                        },
                        "rmsc_xy": {
                            "ann": "0.926",
                            "son": "1.114",
                            "mam": "1.177",
                            "jja": "1.049",
                            "djf": "1.085",
                            "CalendarMonths": []
                        },
                        "some_custom": 1.5,
                        "std-obs_xy": {
                            "ann": "2.493",
                            "son": "3.042",
                            "mam": "2.568",
                            "jja": "2.986",
                            "djf": "2.402",
                            "CalendarMonths": []
                        },
                        "std-obs_xy_devzm": {
                            "ann": "1.569"
                        },
                        "std-obs_xyt": {
                            "ann": "2.835"
                        },
                        "std_xy": {
                            "ann": "2.315",
                            "son": "3.063",
                            "mam": "2.615",
                            "jja": "2.942",
                            "djf": "2.422",
                            "CalendarMonths": []
                        },
                        "std_xy_devzm": {
                            "ann": "1.414"
                        },
                        "std_xyt": {
                            "ann": "2.887"
                        }
                    },
                    "global": {
                        "bias_xy": {
                            "ann": "-0.155",
                            "son": "-0.408",
                            "mam": "-0.009",
                            "jja": "-0.277",
                            "djf": "0.077",
                            "CalendarMonths": []
                        },
                        "cor_xy": {
                            "ann": "0.991",
                            "son": "0.99",
                            "mam": "0.99",
                            "jja": "0.99",
                            "djf": "0.98",
                            "CalendarMonths": []
                        },
                        "custom_ref_min": 271.2738442661475,
                        "mae_xy": {
                            "ann": "1.142",
                            "son": "1.144",
                            "mam": "1.288",
                            "jja": "1.043",
                            "djf": "1.444",
                            "CalendarMonths": []
                        },
                        "mean-obs_xy": {
                            "ann": "291.581",
                            "son": "291.440",
                            "mam": "291.719",
                            "jja": "291.582",
                            "djf": "291.612",
                            "CalendarMonths": []
                        },
                        "mean_xy": {
                            "ann": "291.396",
                            "son": "290.973",
                            "mam": "291.697",
                            "jja": "291.238",
                            "djf": "291.684",
                            "CalendarMonths": []
                        },
                        "rms_devzm": {
                            "ann": "0.907"
                        },
                        "rms_xy": {
                            "ann": "1.418",
                            "son": "1.465",
                            "mam": "1.627",
                            "jja": "1.347",
                            "djf": "1.835",
                            "CalendarMonths": []
                        },
                        "rms_xyt": {
                            "ann": "1.625"
                        },
                        "rms_y": {
                            "ann": "1.265"
                        },
                        "rmsc_xy": {
                            "ann": "1.410",
                            "son": "1.407",
                            "mam": "1.627",
                            "jja": "1.318",
                            "djf": "1.833",
                            "CalendarMonths": []
                        },
                        "some_custom": 1.5,
                        "std-obs_xy": {
                            "ann": "9.822",
                            "son": "9.998",
                            "mam": "10.088",
                            "jja": "9.901",
                            "djf": "9.798",
                            "CalendarMonths": []
                        },
                        "std-obs_xy_devzm": {
                            "ann": "1.741"
                        },
                        "std-obs_xyt": {
                            "ann": "9.982"
                        },
                        "std_xy": {
                            "ann": "9.299",
                            "son": "9.669",
                            "mam": "9.597",
                            "jja": "9.529",
                            "djf": "9.142",
                            "CalendarMonths": []
                        },
                        "std_xy_devzm": {
                            "ann": "1.694"
                        },
                        "std_xyt": {
                            "ann": "9.537"
                        }
                    },
                    "NHEX": {
                        "bias_xy": {
                            "ann": "-1.305",
                            "son": "-1.559",
                            "mam": "-1.260",
                            "jja": "-1.073",
                            "djf": "-1.339",
                            "CalendarMonths": []
                        },
                        "cor_xy": {
                            "ann": "0.986",
                            "son": "0.99",
                            "mam": "0.98",
                            "jja": "0.99",
                            "djf": "0.97",
                            "CalendarMonths": []
                        },
                        "custom_ref_min": 271.2738442661475,
                        "mae_xy": {
                            "ann": "1.530",
                            "son": "1.748",
                            "mam": "1.572",
                            "jja": "1.361",
                            "djf": "1.745",
                            "CalendarMonths": []
                        },
                        "mean-obs_xy": {
                            "ann": "284.155",
                            "son": "286.183",
                            "mam": "281.784",
                            "jja": "286.825",
                            "djf": "281.859",
                            "CalendarMonths": []
                        },
                        "mean_xy": {
                            "ann": "282.816",
                            "son": "284.581",
                            "mam": "280.485",
                            "jja": "285.641",
                            "djf": "280.510",
                            "CalendarMonths": []
                        },
                        "rms_devzm": {
                            "ann": "1.154"
                        },
                        "rms_xy": {
                            "ann": "1.874",
                            "son": "2.092",
                            "mam": "1.983",
                            "jja": "1.732",
                            "djf": "2.180",
                            "CalendarMonths": []
                        },
                        "rms_xyt": {
                            "ann": "2.048"
                        },
                        "rms_y": {
                            "ann": "1.549"
                        },
                        "rmsc_xy": {
                            "ann": "1.345",
                            "son": "1.395",
                            "mam": "1.532",
                            "jja": "1.359",
                            "djf": "1.721",
                            "CalendarMonths": []
                        },
                        "some_custom": 1.5,
                        "std-obs_xy": {
                            "ann": "7.949",
                            "son": "8.619",
                            "mam": "7.334",
                            "jja": "8.742",
                            "djf": "7.360",
                            "CalendarMonths": []
                        },
                        "std-obs_xy_devzm": {
                            "ann": "2.439"
                        },
                        "std-obs_xyt": {
                            "ann": "8.506"
                        },
                        "std_xy": {
                            "ann": "8.167",
                            "son": "8.836",
                            "mam": "7.570",
                            "jja": "8.920",
                            "djf": "7.626",
                            "CalendarMonths": []
                        },
                        "std_xy_devzm": {
                            "ann": "2.515"
                        },
                        "std_xyt": {
                            "ann": "8.695"
                        }
                    },
                    "SHEX": {
                        "bias_xy": {
                            "ann": "1.213",
                            "son": "0.608",
                            "mam": "1.597",
                            "jja": "0.657",
                            "djf": "2.001",
                            "CalendarMonths": []
                        },
                        "cor_xy": {
                            "ann": "0.992",
                            "son": "0.98",
                            "mam": "0.99",
                            "jja": "0.98",
                            "djf": "0.99",
                            "CalendarMonths": []
                        },
                        "custom_ref_min": 271.2935035335274,
                        "mae_xy": {
                            "ann": "1.374",
                            "son": "1.035",
                            "mam": "1.637",
                            "jja": "1.039",
                            "djf": "2.059",
                            "CalendarMonths": []
                        },
                        "mean-obs_xy": {
                            "ann": "282.248",
                            "son": "280.977",
                            "mam": "283.290",
                            "jja": "281.092",
                            "djf": "283.654",
                            "CalendarMonths": []
                        },
                        "mean_xy": {
                            "ann": "283.458",
                            "son": "281.581",
                            "mam": "284.885",
                            "jja": "281.751",
                            "djf": "285.650",
                            "CalendarMonths": []
                        },
                        "rms_devzm": {
                            "ann": "0.806"
                        },
                        "rms_xy": {
                            "ann": "1.613",
                            "son": "1.346",
                            "mam": "1.901",
                            "jja": "1.359",
                            "djf": "2.407",
                            "CalendarMonths": []
                        },
                        "rms_xyt": {
                            "ann": "1.854"
                        },
                        "rms_y": {
                            "ann": "1.383"
                        },
                        "rmsc_xy": {
                            "ann": "1.063",
                            "son": "1.200",
                            "mam": "1.032",
                            "jja": "1.190",
                            "djf": "1.338",
                            "CalendarMonths": []
                        },
                        "some_custom": 1.5,
                        "std-obs_xy": {
                            "ann": "7.168",
                            "son": "6.773",
                            "mam": "7.589",
                            "jja": "6.712",
                            "djf": "7.638",
                            "CalendarMonths": []
                        },
                        "std-obs_xy_devzm": {
                            "ann": "1.545"
                        },
                        "std-obs_xyt": {
                            "ann": "7.320"
                        },
                        "std_xy": {
                            "ann": "6.591",
                            "son": "6.439",
                            "mam": "6.987",
                            "jja": "6.432",
                            "djf": "6.646",
                            "CalendarMonths": []
                        },
                        "std_xy_devzm": {
                            "ann": "1.589"
                        },
                        "std_xyt": {
                            "ann": "6.937"
                        }
                    }
                }
            },
            "InputRegionMD5": "e3b7143d72d6b4824e20dabd80acd869",
            "InputClimatologyFileName": "tos_GFDL-ESM2G_Omon_historical_r1i1p1_198501-200512-clim.nc",
            "units": "K",
            "InputClimatologyMD5": "974a3339d34fcdd6a68d6e135f72cd78",
            "InputRegionFileName": "sftlf_GFDL-ESM2G.nc"
        }
    },
    "Variable": {
        "id": "tos"
    },
    "json_version": 3.0,
    "References": {
        "default": {
            "RefName": "UKMETOFFICE-HadISST-v1-1",
            "MD5sum": "41833b403cad7052773dd933d1798a14",
            "period": "198002-200501",
            "filename": "tos_pcmdi-metrics_Omon_UKMETOFFICE-HadISST-v1-1_198002-200501-clim.nc",
            "shape": "(12, 180, 360)",
            "CMIP_CMOR_TABLE": "Omon",
            "RefTrackingDate": "Wed Jan 15 10:57:20 2014"
        }
    },
    "RegionalMasking": {
        "TROPICS": {
            "domain": {
                "TROPICS": "cdutil.region.domain(latitude=(-30.0, 30))"
            },
            "id": "TROPICS"
        },
        "global": {
            "id": "global"
        },
        "NHEX": {
            "domain": {
                "NHEX": "cdutil.region.domain(latitude=(30.0, 90))"
            },
            "id": "NHEX"
        },
        "SHEX": {
            "domain": {
                "SHEX": "cdutil.region.domain(latitude=(-90.0, -30))"
            },
            "id": "SHEX"
        }
    },
    "GridInfo": {
        "GridResolution": [
            72,
            144
        ],
        "GridName": "2.5x2.5",
        "RegridMethod": "linear",
        "RegridTool": "esmf"
    },
    "METRICS": {
        "rms_xyt": {
            "Abstract": "Compute Spatial and Temporal Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatio-Temporal Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "rms_xy": {
            "Abstract": "Compute Spatial Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "rmsc_xy": {
            "Abstract": "Compute Centered Spatial Root Mean Square",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "bias_xy": {
            "Abstract": "Compute Full Average of Model - Observation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Bias"
        },
        "mae_xy": {
            "Abstract": "Compute Full Average of Absolute Difference Between Model And Observation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Mean Absolute Error"
        },
        "cor_xy": {
            "Abstract": "Compute Spatial Correlation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Correlation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "mean_xy": {
            "Abstract": "Area Mean (area weighted)",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Mean"
        },
        "std_xy": {
            "Abstract": "Compute Spatial Standard Deviation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial Standard Deviation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "std_xyt": {
            "Abstract": "Compute Space-Time Standard Deviation",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Spatial-temporal Standard Deviation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "seasonal_mean": {
            "Abstract": "Compute Seasonal Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Seasonal Mean",
            "Comments": "Assumes input are 12 months climatology"
        },
        "annual_mean": {
            "Abstract": "Compute Annual Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Annual Mean",
            "Comments": "Assumes input are 12 months climatology",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "zonal_mean": {
            "Abstract": "Compute Zonal Mean",
            "Contact": "pcmdi-metrics@llnl.gov",
            "Name": "Zonal Mean",
            "Comments": "",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "some_custom": {
            "Abstract": "For demo purpose really does nothing",
            "Contact": "doutriaux1@llnl.gov",
            "Name": "SomeCustom"
        },
        "custom_ref_min": {
            "Abstract": "Computes Custom Minimum for demo purposes",
            "Contact": "doutriaux1@llnl.gov",
            "Name": "Custom Minimum"
        }
    },
    "json_structure": [
        "model",
        "reference",
        "rip",
        "region",
        "statistic",
        "season"
    ],
    "provenance": {
        "platform": {
            "OS": "Darwin",
            "Version": "16.7.0",
            "Name": "loki"
        },
        "userId": "doutriaux1",
        "osAccess": false,
        "commandLine": "/Users/doutriaux1/anaconda2/envs/cdat8/bin/pcmdi_metrics_driver.py -p /git/pcmdi_metrics/tests/pcmdi/basic_test_parameters_file.py",
        "date": "2018-05-03 09:24:14",
        "conda": {
            "Version": "4.5.1",
            "buildVersion": "3.9.1",
            "PythonVersion": "2.7.14.final.0",
            "Platform": "osx-64"
        },
        "packages": {
            "blas": "1.0.1",
            "cdms": "3.0",
            "CDP": "1.3.2",
            "cdtime": "3.0",
            "cdutil": "8.0",
            "clapack": "3.2.1",
            "lapack": "3.6.1",
            "esmf": "7.1.0r",
            "esmpy": "7.1.0r",
            "genutil": "8.0",
            "python": "2.7.14",
            "matplotlib": "2.2.2",
            "mesalib": "17.2.0",
            "numpy": "1.14.2",
            "vcs": "8.0.2018.04.27.14.53.gfc2e5fc5",
            "vtk": "8.0.1.8.0",
            "PMP": "ga068fe0",
            "PMPObs": null
        },
        "openGL": {
            "vendor": "ATI Technologies Inc.",
            "renderer": "AMD Radeon Pro 455 OpenGL Engine",
            "version": "2.1 ATI-1.51.8",
            "shading language version": "1.20",
            "GLX": {
                "client": {
                    "vendor": "Mesa Project and SGI",
                    "version": "1.4"
                },
                "version": "1.4",
                "server": {
                    "vendor": "SGI",
                    "version": "1.4"
                }
            }
        }
    }
}