package:
    name: pcmdi_metrics
    version: 1.2

source:
    git_url: git://github.com/PCMDI/pcmdi_metrics
    git_rev: v1.2

build:
    script: python setup.py install
    number: 0

requirements:
  build:
    - python {{ python}}
    - setuptools
    - numpy
  run:
    - python {{ python }}
    - vcs ==8.0
    - vcsaddons ==8.0
    - cdms2 ==3.0.1
    - genutil
    - cdutil ==8.0
    - cdp >=1.4.0
    - numpy
    - cia ==0.0.6
    - proj4 <5


about:
    home:  http://gitub.com/PCMDI/pcmdi_metrics
    summary: The PCMDI metrics package is used to objectively compare results from climate models with observations using well-established statistical tests. Results are produced in the context of all model simulations contributed to CMIP5 and earlier CMIP phases. Among other purposes, this enables modeling groups to evaluate changes during the development cycle in the context of the structural error distribution of the multi-model ensemble. Currently, the comparisons are focused on large- to global-scale annual cycle performance metrics.

